[deploy]
bucket = 'cfn-artifacts-cloud-bootcamp'
region = 'us-east-1'
stack_name = 'CrdSyncRole'

[parameters]
GitHubOrg = 'rahuulaws'
RepositoryName = '-aws-bootcamp-cruddur-2023'
OIDCProviderArn = ''