[deploy]
bucket = 'cfn-artifacts-cloud-bootcamp'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]

ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'production'
GithubRepo = 'rahuulaws/-aws-bootcamp-cruddur-2023'
ArtifactBucketName = "codepipeline-cruddur-artifacts-cfn"